2021-03-05 20:38:43,965 INFO Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
2021-03-05 20:38:43,974 INFO Microsoft.Hosting.Lifetime - Hosting environment: Development
2021-03-05 20:38:43,977 INFO Microsoft.Hosting.Lifetime - Content root path: C:\Users\Uvi\Documents\VStudio 2019\ASP.Net Core\ExceptionLogging\ExceptionLogging
2021-03-05 20:38:44,150 ERROR ExceptionLogging.Models.LoggerManager - Exception Happened In Index and Handled in OnException
2021-03-05 20:38:44,258 ERROR ExceptionLogging.Models.LoggerManager -    at ExceptionLogging.Controllers.HomeController.Index() in C:\Users\Uvi\Documents\VStudio 2019\ASP.Net Core\ExceptionLogging\ExceptionLogging\Controllers\HomeController.cs:line 24
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-03-05 20:39:10,379 ERROR ExceptionLogging.Models.LoggerManager - Exception Happened in Privacy and Handled in Controller
2021-03-05 20:39:10,380 ERROR ExceptionLogging.Models.LoggerManager -    at ExceptionLogging.Controllers.HomeController.Privacy() in C:\Users\Uvi\Documents\VStudio 2019\ASP.Net Core\ExceptionLogging\ExceptionLogging\Controllers\HomeController.cs:line 32
